language: python
python:
- '3.6'
addons:
  ssh_known_hosts: "$SERVER_NS"
services:
- mysql
install:
- pip install -r requirements.txt
- echo "DB_NAME=thermo" > .env
- echo "DB_USER=root" >> .env
- echo "DB_PASSWORD=" >> .env
- echo "DB_HOST=localhost" >> .env
- echo "DEBUG=False" >> .env
before_script:
- echo -e "Host $SERVER_NS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- mysql -e 'create database thermo;' -u root
- python manage.py migrate
script: python manage.py test
before_deploy:
- openssl aes-256-cbc -K $encrypted_ec85574b3970_key -iv $encrypted_ec85574b3970_iv -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ $SSH_USER@$SERVER_NS:$SSH_PATH
  on:
    branch: master