language: node_js
node_js:
- '6.10'
addons:
  ssh_known_hosts: "$SERVER_NS"
install:
- npm install
script: ng build --prod
before_deploy:
- openssl aes-256-cbc -K $encrypted_ec85574b3970_key -iv $encrypted_ec85574b3970_iv -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist $SSH_USER@$SERVER_NS:$SSH_PATH
  on:
    branch: master